server:
  port: 8083

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
