spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
