spring:
  profiles:
    active: dev

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: health.assistant.back@gmail.com
    password: yrze lrll auvp zhks
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

