spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: HealthAssistant

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
  mail:
    host: smtp.gmail.com
    port: 587
    username: health.assistant.back@gmail.com
    password: yrze lrll auvp zhks
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

